version: '2'

services:
    mysql:
        image: devdrops/magento-mysql:latest
        env_file:
            - .env
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "3307:3306"

    magento:
        image: ricardotulio/ecommerce-platforms
        volumes:
            - ./www/:/var/www/
        ports:
            - "8080:80"
            - "80:80"
        depends_on:
            - mysql
